#!/usr/bin/env python3
"""
diagnostics/mismatch_catcher.py
================================
One-time QC pipeline that verifies Fiji-generated section thumbnails against
reference thumbnails, resolves any naming or orientation mismatches, and
applies the resulting corrections to all downstream file types.

Background
----------
Free-floating brain sections are mounted without a consistent orientation.
The Fiji conversion script (00a_vsi_to_tiff.py) assigns slice IDs based on
acquisition order, but the order in which sections were picked up from the
PBS tray may differ from the order in which they were originally numbered.
This script uses SSIM-based image matching to verify that each generated
thumbnail corresponds to the correct reference thumbnail, and applies
horizontal flips where needed to standardise hemisphere orientation.

Pipeline stages
---------------
  Stage 1  — SSIM cross-match: generated vs reference thumbnails
             → MASTER_MATCHING_SUMMARY.csv
  Stage 2  — Rigorous per-channel SSIM + histogram correlation + PSNR
             → RIGOROUS_ANALYSIS_REPORT.csv  (+ diff maps for low confidence)
  Stage 3  — Recovery pass for mismatches (green-channel exhaustive search)
             → RECOVERY_REPORT.csv
  Stage 4  — FINAL_RENAME_LIST.csv from rigorous report
  Stage 5  — QC threshold split
             → RE_ANALYZE_LIST.csv, VERIFIED_LIST.csv
  Stage 6  — Morphology engine (Sobel + CLAHE) for remaining low-confidence
             → MORPHOLOGY_RECOVERY_REPORT.csv
  Stage 7  — Visual gallery for morphology results
  Stage 8  — Mirror-aware recovery (normal + fliplr comparison)
             → MIRROR_RECOVERY_REPORT.csv
  Stage 9  — Visual gallery for mirror results
  Stage 10 — Consolidate verified + morphology + mirror
             → PROJECT_GOLDEN_MASTER_LIST.csv
  Stage 11 — Visual audit gallery from golden master
  Stage 12 — Apply golden master: rename + mirror split_8bit TIFFs
             → /path/to/FINAL_PREPPED/
  Stage 13 — Apply to C1 CPN prediction PNGs (in-place)
  Stage 14 — Apply to C2 CPN prediction PNGs (in-place)
  Stage 15 — Rename counts CSVs in DATA/{animal}/counts/
  Stage 16 — Copy + mirror hiRes TIFFs → HIRES_FINAL/
  Stage 17 — Integrity audit (file exists + size check)
  Stage 18 — Safe structure swap (backup old DATA, move HIRES_FINAL to DATA)
  Stage 19 — Restore subfolders from backup into new DATA structure
  Stage 20 — Apply golden master to original multi-channel TIFFs
             → /path/to/ORIGINALS_RENAMED/
  Stage 21 — C3 symmetry audit (injection side check)
             → C3_Symmetry_Audit.csv
  Stage 22 — Mirror C3-flagged files in-place
  Stage 23 — Verification pass → FINAL_ORIENTATION_VERIFICATION.csv
  Stage 24 — Visual comparison gallery vs reference thumbnails
  Stage 25 — Manual flip of residual files identified from gallery review
  Stage 26 — Produce FINAL_TIFF_TRANSFORMATION_LOG.csv

The FINAL_TIFF_TRANSFORMATION_LOG.csv produced by Stage 26 is the input
to diagnostics/fix_c3_csv_coordinates.py, which applies the corresponding
coordinate correction to Cellpose detection CSVs.

Usage
-----
Run stages sequentially. Each stage reads the CSV output of the previous
one, so stopping between stages for manual review is expected and encouraged
(particularly after Stages 7 and 11 before committing to the file operations
in Stages 12–20).

    python diagnostics/mismatch_catcher.py

To run only specific stages, comment out the function calls at the bottom
of this file.

Requirements
------------
    pip install numpy pandas scikit-image tqdm pillow matplotlib
"""

import gc
import os
import re
import shutil
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from PIL import Image, ImageDraw
from skimage import exposure, filters, io, transform, util
from skimage.metrics import peak_signal_noise_ratio as psnr
from skimage.metrics import structural_similarity as ssim
from tqdm import tqdm

Image.MAX_IMAGE_PIXELS = None   # suppress PIL decompression-bomb warnings

# =============================================================================
# CONFIGURATION
# =============================================================================
# ── Input paths ───────────────────────────────────────────────────────────────
# Reference thumbnails from original acquisition (T7 drive or equivalent)
# Structure: REF_BASE/{group}/{animal}/*.jpg
REF_BASE = Path("/path/to/reference_thumbnails")

# Thumbnails generated by Fiji (00b_generate_quint_thumbnails.py)
# Structure: GEN_BASE/{animal}/*.jpg
GEN_BASE = Path("/path/to/thum_generated")

# Original multi-channel TIFFs (source for 00_split_and_convert_8bit.py)
SOURCE_ROOT = Path("/path/to/originals")

# Project DATA root (contains hiRes, counts, masks, etc. per animal)
DATA_BASE = Path("/path/to/DATA")

# Split 8-bit output (from 00_split_and_convert_8bit.py)
SPLIT_8BIT_BASE = Path("/path/to/split_8bit")

# CPN prediction PNGs — C1 (PNN) and C2 (PV)
CPN_OUTPUT_C1 = Path("/path/to/CPN_output_C1")
CPN_OUTPUT_C2 = Path("/path/to/CPN_output_C2")

# ── Output paths ──────────────────────────────────────────────────────────────
REPORT_DIR       = Path("/path/to/matching_reports")
DETAILED_DIR     = Path("/path/to/detailed_analysis")
RECOVERY_DIR     = Path("/path/to/recovery_results")
QC_DIR           = Path("/path/to/quality_control")
MORPH_DIR        = Path("/path/to/morphology_recovery")
MIRROR_DIR       = Path("/path/to/mirror_recovery")
AUDIT_DIR        = Path("/path/to/FINAL_VISUAL_AUDIT")
FINAL_PREPPED    = Path("/path/to/FINAL_PREPPED")
HIRES_FINAL      = Path("/path/to/HIRES_FINAL")
ORIGINALS_RENAMED= Path("/path/to/ORIGINALS_RENAMED")
GALLERY_OUT      = Path("/path/to/FINAL_COMPARISON_GALLERY")

# ── QC thresholds ─────────────────────────────────────────────────────────────
# Slices with Rigorous_Confidence below this are sent to morphology recovery
CONFIDENCE_THRESHOLD = 0.59

# Morphology scores below this are sent to mirror-aware recovery
MIRROR_THRESHOLD = 0.40

# ── Orientation convention ────────────────────────────────────────────────────
# Which side of the image should carry the stronger C3 (mScarlet) signal
# after all corrections. Injection was ipsilateral; set to match your convention.
EXPECTED_SIDE = "right"

# ── Manual flip list ──────────────────────────────────────────────────────────
# Filenames identified from the Stage 24 gallery review that require an
# additional flip beyond what the automated pipeline applied.
# Populate from your own gallery inspection — leave empty for a fresh run.
MANUAL_FLIP_LIST: list = []

# Subfolders to restore into DATA after the structure swap (Stage 19)
FOLDERS_TO_RESTORE = ["counts", "lowRes", "processed", "RGBatlas", "masks"]

# =============================================================================
# SHARED UTILITIES
# =============================================================================

def extract_slice_id(filename: str):
    m = re.search(r"(s\d+)", filename)
    return m.group(1) if m else None


def load_gray_300(path) -> np.ndarray:
    """Load image, resize to 300×300, return grayscale float array."""
    try:
        img = io.imread(path)
        img_small = transform.resize(img, (300, 300), anti_aliasing=True)
        return np.mean(img_small, axis=2) if img_small.ndim == 3 else img_small
    except Exception as e:
        print(f"  Error loading {path}: {e}")
        return None


def load_green_300(path) -> np.ndarray:
    """Load image, resize to 300×300, return green channel (most structural)."""
    try:
        img = io.imread(path)
        img_small = transform.resize(img, (300, 300), anti_aliasing=True)
        return img_small[:, :, 1] if img_small.ndim == 3 else img_small
    except Exception:
        return None


def morphology_map(path) -> np.ndarray:
    """Sobel edge map after CLAHE normalisation — orientation/colour invariant."""
    try:
        img = io.imread(path)
        img = transform.resize(img, (400, 400), anti_aliasing=True)
        gray = img[:, :, 1] if img.ndim == 3 else img
        gray = exposure.equalize_adapthist(gray)
        return filters.sobel(gray)
    except Exception:
        return None


def find_ref_folder(animal: str) -> Path | None:
    matches = [m for m in REF_BASE.rglob(animal) if m.is_dir()]
    return matches[0] if matches else None

# =============================================================================
# STAGE 1 — SSIM cross-match
# =============================================================================

def stage1_ssim_crossmatch():
    print("\n=== Stage 1: SSIM cross-match ===")
    REPORT_DIR.mkdir(parents=True, exist_ok=True)

    animal_folders = [f for f in GEN_BASE.iterdir() if f.is_dir()]
    all_results = []

    for gen_folder in tqdm(animal_folders, desc="Animals"):
        animal_id = gen_folder.name
        ref_folder = find_ref_folder(animal_id)
        if not ref_folder:
            print(f"  WARNING: {animal_id} not found in REF_BASE")
            continue

        ref_data = {}
        for f in ref_folder.glob("*.jpg"):
            if f.name.startswith("._"):
                continue
            sid = extract_slice_id(f.name)
            if sid:
                img = load_gray_300(f)
                if img is not None:
                    ref_data[sid] = img

        gen_data = {}
        for f in gen_folder.glob("*.jpg"):
            if f.name.startswith("._"):
                continue
            sid = extract_slice_id(f.name)
            if sid:
                img = load_gray_300(f)
                if img is not None:
                    gen_data[sid] = img

        if not ref_data or not gen_data:
            print(f"  Skipping {animal_id}: missing JPGs")
            continue

        for g_id, g_img in gen_data.items():
            best_score, best_match = -1, None
            for r_id, r_img in ref_data.items():
                score = ssim(g_img, r_img, data_range=1.0)
                if score > best_score:
                    best_score, best_match = score, r_id

            status = "OK" if g_id == best_match else "MISMATCH"
            if best_score < 0.85:
                status += " (LOW CONFIDENCE)"
            all_results.append({
                "Animal": animal_id,
                "HiRes_Filename_ID": g_id,
                "Matched_Thumbnail_ID": best_match,
                "Similarity_Score": round(best_score, 4),
                "Status": status,
            })

    df = pd.DataFrame(all_results)
    out = REPORT_DIR / "MASTER_MATCHING_SUMMARY.csv"
    df.to_csv(out, index=False)
    print(f"  Saved: {out}  ({len(df)} rows, "
          f"{df['Status'].str.contains('MISMATCH').sum()} mismatches)")
    return df

# =============================================================================
# STAGE 2 — Rigorous per-channel analysis
# =============================================================================

def stage2_rigorous_analysis():
    print("\n=== Stage 2: Rigorous per-channel analysis ===")
    DETAILED_DIR.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(REPORT_DIR / "MASTER_MATCHING_SUMMARY.csv")
    results = []

    for _, row in tqdm(df.iterrows(), total=len(df)):
        animal, gen_id, ref_id = row["Animal"], row["HiRes_Filename_ID"], row["Matched_Thumbnail_ID"]

        ref_folder = find_ref_folder(animal)
        if not ref_folder:
            continue
        gen_files = list((GEN_BASE / animal).glob(f"*{gen_id}.jpg"))
        ref_files = list(ref_folder.glob(f"*{ref_id}.jpg"))
        if not gen_files or not ref_files:
            continue

        img_gen = io.imread(gen_files[0])
        img_ref = io.imread(ref_files[0])

        h, w = img_ref.shape[:2]
        img_gen_r = transform.resize(
            img_gen, (h, w), anti_aliasing=True, preserve_range=True
        ).astype(np.uint8)

        s_r = ssim(img_ref[:, :, 0], img_gen_r[:, :, 0], data_range=255)
        s_g = ssim(img_ref[:, :, 1], img_gen_r[:, :, 1], data_range=255)
        s_b = ssim(img_ref[:, :, 2], img_gen_r[:, :, 2], data_range=255)

        from skimage import color as skcolor
        h1 = np.histogram(skcolor.rgb2gray(img_ref),    bins=256, range=(0, 255))[0]
        h2 = np.histogram(skcolor.rgb2gray(img_gen_r),  bins=256, range=(0, 255))[0]
        hist_corr = np.corrcoef(h1, h2)[0, 1]

        try:
            p_val = psnr(img_ref, img_gen_r, data_range=255)
        except Exception:
            p_val = 0

        global_conf = (s_r + s_g + hist_corr) / 3
        full_row = row.to_dict()
        full_row.update({
            "SSIM_Red": round(s_r, 4), "SSIM_Green": round(s_g, 4),
            "SSIM_Blue": round(s_b, 4), "Hist_Corr": round(hist_corr, 4),
            "PSNR": round(p_val, 2), "Rigorous_Confidence": round(global_conf, 4),
        })
        results.append(full_row)

        if global_conf < 0.7:
            fig, ax = plt.subplots(1, 3, figsize=(18, 6))
            ax[0].imshow(img_ref);   ax[0].set_title(f"Ref: {ref_id}")
            ax[1].imshow(img_gen);   ax[1].set_title(f"Gen: {gen_id}")
            diff = np.abs(
                img_ref.astype(float) -
                transform.resize(img_gen, img_ref.shape[:2], preserve_range=True)
            )
            ax[2].imshow(np.mean(diff, axis=2), cmap="hot")
            ax[2].set_title("Difference")
            for a in ax:
                a.axis("off")
            plt.suptitle(f"{animal} | Conf: {global_conf:.2f}")
            plt.savefig(DETAILED_DIR / f"diff_{animal}_{gen_id}.png")
            plt.close()

    df_out = pd.DataFrame(results)
    out = DETAILED_DIR / "RIGOROUS_ANALYSIS_REPORT.csv"
    df_out.to_csv(out, index=False)
    print(f"  Saved: {out}")
    return df_out

# =============================================================================
# STAGE 3 — Recovery pass for mismatches
# =============================================================================

def stage3_recovery():
    print("\n=== Stage 3: Recovery pass ===")
    RECOVERY_DIR.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(DETAILED_DIR / "RIGOROUS_ANALYSIS_REPORT.csv")
    mismatches = df[df["Status"].str.contains("MISMATCH")].copy()
    if mismatches.empty:
        print("  No mismatches — nothing to recover.")
        return

    recovery_data = []
    for animal, group in tqdm(mismatches.groupby("Animal"), desc="Animals"):
        ref_folder = find_ref_folder(animal)
        if not ref_folder:
            continue
        ref_pool = {}
        for f in ref_folder.glob("*.jpg"):
            if f.name.startswith("._"):
                continue
            sid = re.search(r"(s\d+)", f.name)
            if sid:
                img = load_green_300(f)
                if img is not None:
                    ref_pool[sid.group(1)] = img

        for _, row in group.iterrows():
            gen_id = row["HiRes_Filename_ID"]
            gen_files = list((GEN_BASE / animal).glob(f"*{gen_id}.jpg"))
            if not gen_files:
                continue
            gen_img = load_green_300(gen_files[0])
            if gen_img is None:
                continue

            best_score, best_id = -1, None
            for r_id, r_img in ref_pool.items():
                score = ssim(gen_img, r_img, data_range=1.0)
                if score > best_score:
                    best_score, best_id = score, r_id

            recovery_data.append({
                "Animal": animal,
                "HiRes_Slice": gen_id,
                "Original_Wrong_Match": row["Matched_Thumbnail_ID"],
                "New_Recovered_Match": best_id,
                "Recovery_Score": round(best_score, 4),
                "Note": "Corrected" if gen_id == best_id else "Still Mismatched",
            })

    df_out = pd.DataFrame(recovery_data)
    out = RECOVERY_DIR / "RECOVERY_REPORT.csv"
    df_out.to_csv(out, index=False)
    corrected = (df_out["Note"] == "Corrected").sum()
    print(f"  Corrected {corrected}/{len(mismatches)} mismatches. Saved: {out}")

# =============================================================================
# STAGE 4 — FINAL_RENAME_LIST.csv
# =============================================================================

def stage4_rename_list():
    print("\n=== Stage 4: Produce rename list ===")
    df = pd.read_csv(DETAILED_DIR / "RIGOROUS_ANALYSIS_REPORT.csv")
    mismatches = df[df["HiRes_Filename_ID"] != df["Matched_Thumbnail_ID"]].copy()

    if mismatches.empty:
        print("  No mismatches — all slices correctly labelled.")
        return

    rename_list = mismatches[
        ["Animal", "HiRes_Filename_ID", "Matched_Thumbnail_ID", "Rigorous_Confidence"]
    ].copy()
    rename_list.columns = ["Animal", "Current_Filename_ID", "Correct_Reference_ID", "Match_Confidence"]
    out = REPORT_DIR / "FINAL_RENAME_LIST.csv"
    rename_list.to_csv(out, index=False)
    print(f"  {len(rename_list)} discrepancies. Saved: {out}")
    print(rename_list.sort_values(["Animal", "Current_Filename_ID"]).to_string(index=False))

# =============================================================================
# STAGE 5 — QC threshold split
# =============================================================================

def stage5_qc_split():
    print(f"\n=== Stage 5: QC split at confidence {CONFIDENCE_THRESHOLD} ===")
    QC_DIR.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(DETAILED_DIR / "RIGOROUS_ANALYSIS_REPORT.csv")
    re_analyze = df[df["Rigorous_Confidence"] < CONFIDENCE_THRESHOLD]
    verified   = df[df["Rigorous_Confidence"] >= CONFIDENCE_THRESHOLD]

    re_analyze.to_csv(QC_DIR / "RE_ANALYZE_LIST.csv", index=False)
    verified.to_csv(  QC_DIR / "VERIFIED_LIST.csv",   index=False)

    print(f"  Review required (<{CONFIDENCE_THRESHOLD}): {len(re_analyze)}")
    print(f"  Verified (>={CONFIDENCE_THRESHOLD}):       {len(verified)}")
    if not re_analyze.empty:
        print(re_analyze["Animal"].value_counts().to_string())

# =============================================================================
# STAGE 6 — Morphology recovery (Sobel + CLAHE)
# =============================================================================

def stage6_morphology_recovery():
    print("\n=== Stage 6: Morphology recovery ===")
    MORPH_DIR.mkdir(parents=True, exist_ok=True)

    df_re = pd.read_csv(QC_DIR / "RE_ANALYZE_LIST.csv")
    results = []

    for animal, group in tqdm(df_re.groupby("Animal"), desc="Animals"):
        ref_folder = find_ref_folder(animal)
        if not ref_folder:
            continue
        ref_pool = {}
        for f in ref_folder.glob("*.jpg"):
            if f.name.startswith("._"):
                continue
            sid = re.search(r"(s\d+)", f.name)
            if sid:
                m = morphology_map(f)
                if m is not None:
                    ref_pool[sid.group(1)] = m

        for _, row in group.iterrows():
            gen_id = row["HiRes_Filename_ID"]
            gen_files = list((GEN_BASE / animal).glob(f"*{gen_id}.jpg"))
            if not gen_files:
                continue
            gen_map = morphology_map(gen_files[0])
            if gen_map is None:
                continue

            best_score, best_id = -1, None
            for r_id, r_map in ref_pool.items():
                score = ssim(gen_map, r_map, data_range=r_map.max() - r_map.min())
                if score > best_score:
                    best_score, best_id = score, r_id

            results.append({
                "Animal": animal,
                "Original_HiRes_ID": gen_id,
                "New_Suggested_Match": best_id,
                "Morphology_Score": round(best_score, 4),
                "Status": "Corrected" if gen_id != best_id else "Verified_Original",
            })

    df_out = pd.DataFrame(results)
    out = MORPH_DIR / "MORPHOLOGY_RECOVERY_REPORT.csv"
    df_out.to_csv(out, index=False)
    print(f"  Saved: {out}")
    print(df_out.head().to_string(index=False))

# =============================================================================
# STAGE 7 — Visual gallery for morphology results
# =============================================================================

def stage7_morphology_gallery():
    print("\n=== Stage 7: Morphology visual gallery ===")
    vis_dir = MORPH_DIR / "visual_verification"
    vis_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(MORPH_DIR / "MORPHOLOGY_RECOVERY_REPORT.csv")
    for _, row in df.iterrows():
        animal  = row["Animal"]
        gen_id  = row["Original_HiRes_ID"]
        ref_id  = row["New_Suggested_Match"]
        score   = row["Morphology_Score"]
        status  = row["Status"]

        gen_files = list((GEN_BASE / animal).glob(f"*{gen_id}.jpg"))
        ref_folder = find_ref_folder(animal)
        if not ref_folder or not gen_files:
            continue
        ref_files = list(ref_folder.glob(f"*{ref_id}.jpg"))
        if not ref_files:
            continue

        fig, axes = plt.subplots(1, 2, figsize=(16, 8))
        axes[0].imshow(io.imread(ref_files[0]))
        axes[0].set_title(f"REFERENCE: {ref_id}", fontsize=14, color="blue")
        axes[0].axis("off")
        axes[1].imshow(io.imread(gen_files[0]))
        axes[1].set_title(f"GENERATED: {gen_id}\nScore: {score:.4f}",
                          fontsize=14, color="green" if status == "Corrected" else "orange")
        axes[1].axis("off")
        plt.suptitle(f"{animal} | {status}", fontsize=18, fontweight="bold")
        plt.savefig(vis_dir / f"{animal}_{gen_id}_vs_{ref_id}.png", bbox_inches="tight")
        plt.close()
    print(f"  Gallery saved to: {vis_dir}")

# =============================================================================
# STAGE 8 — Mirror-aware recovery
# =============================================================================

def stage8_mirror_recovery():
    print(f"\n=== Stage 8: Mirror-aware recovery (threshold {MIRROR_THRESHOLD}) ===")
    MIRROR_DIR.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(MORPH_DIR / "MORPHOLOGY_RECOVERY_REPORT.csv")
    low = df[df["Morphology_Score"] < MIRROR_THRESHOLD].copy()
    if low.empty:
        print(f"  No slices below {MIRROR_THRESHOLD}.")
        return

    mirror_results = []
    for animal, group in tqdm(low.groupby("Animal"), desc="Animals"):
        ref_folder = find_ref_folder(animal)
        if not ref_folder:
            continue
        ref_pool = {}
        for f in ref_folder.glob("*.jpg"):
            if f.name.startswith("._"):
                continue
            sid = re.search(r"(s\d+)", f.name)
            if sid:
                m = morphology_map(f)
                if m is not None:
                    ref_pool[sid.group(1)] = {
                        "normal": m, "mirrored": np.fliplr(m)
                    }

        for _, row in group.iterrows():
            gen_id = row["Original_HiRes_ID"]
            gen_files = list((GEN_BASE / animal).glob(f"*{gen_id}.jpg"))
            if not gen_files:
                continue
            gen_map = morphology_map(gen_files[0])
            if gen_map is None:
                continue

            best_score, best_id, was_mirrored = -1, None, False
            for r_id, orientations in ref_pool.items():
                for key, candidate in orientations.items():
                    score = ssim(gen_map, candidate,
                                 data_range=candidate.max() - candidate.min())
                    if score > best_score:
                        best_score = score
                        best_id = r_id
                        was_mirrored = (key == "mirrored")

            mirror_results.append({
                "Animal": animal,
                "HiRes_ID": gen_id,
                "Previous_Match": row["New_Suggested_Match"],
                "New_Match": best_id,
                "New_Score": round(best_score, 4),
                "Is_Mirrored": was_mirrored,
                "Status": "Mirror_Corrected" if was_mirrored else "Verified_Orientation",
            })

    df_out = pd.DataFrame(mirror_results)
    out = MIRROR_DIR / "MIRROR_RECOVERY_REPORT.csv"
    df_out.to_csv(out, index=False)
    print(f"  Saved: {out}")

# =============================================================================
# STAGE 9 — Mirror visual gallery
# =============================================================================

def stage9_mirror_gallery():
    print("\n=== Stage 9: Mirror visual gallery ===")
    vis_dir = MIRROR_DIR / "visual_verification"
    vis_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(MIRROR_DIR / "MIRROR_RECOVERY_REPORT.csv")
    for _, row in df.iterrows():
        animal  = row["Animal"]
        gen_id  = row["HiRes_ID"]
        ref_id  = row["New_Match"]
        mirrored = row["Is_Mirrored"]
        score   = row["New_Score"]

        gen_files = list((GEN_BASE / animal).glob(f"*{gen_id}.jpg"))
        ref_folder = find_ref_folder(animal)
        if not ref_folder or not gen_files:
            continue
        ref_files = list(ref_folder.glob(f"*{ref_id}.jpg"))
        if not ref_files:
            continue

        img_gen = io.imread(gen_files[0])
        img_ref = io.imread(ref_files[0])
        display_ref = np.fliplr(img_ref) if mirrored else img_ref

        fig, axes = plt.subplots(1, 2, figsize=(16, 8))
        axes[0].imshow(display_ref)
        axes[0].set_title(
            f"REFERENCE: {ref_id}" + ("\n(MIRRORED TO MATCH)" if mirrored else ""),
            fontsize=14, color="blue"
        )
        axes[0].axis("off")
        axes[1].imshow(img_gen)
        axes[1].set_title(f"GENERATED: {gen_id}\nScore: {score:.4f}",
                          fontsize=14, color="green" if mirrored else "orange")
        axes[1].axis("off")
        plt.suptitle(f"{animal} | Is_Mirrored: {mirrored}", fontsize=18, fontweight="bold")
        plt.savefig(vis_dir / f"MIRROR_{animal}_{gen_id}_vs_{ref_id}.png", bbox_inches="tight")
        plt.close()
    print(f"  Gallery saved to: {vis_dir}")

# =============================================================================
# STAGE 10 — Consolidate into golden master
# =============================================================================

def stage10_golden_master():
    print("\n=== Stage 10: Consolidate golden master ===")

    def load_std(path, source_type):
        if not path.exists():
            print(f"  Warning: {path.name} not found.")
            return pd.DataFrame()
        df = pd.read_csv(path)
        if source_type == "verified":
            df = df[["Animal", "HiRes_Filename_ID", "Matched_Thumbnail_ID",
                      "Rigorous_Confidence"]].copy()
            df.columns = ["Animal", "HiRes_ID", "Correct_ID", "Score"]
            df["Needs_Mirroring"] = False
        elif source_type == "morphology":
            df = df[["Animal", "Original_HiRes_ID", "New_Suggested_Match",
                      "Morphology_Score"]].copy()
            df.columns = ["Animal", "HiRes_ID", "Correct_ID", "Score"]
            df["Needs_Mirroring"] = False
        elif source_type == "mirror":
            df = df[["Animal", "HiRes_ID", "New_Match",
                      "New_Score", "Is_Mirrored"]].copy()
            df.columns = ["Animal", "HiRes_ID", "Correct_ID", "Score", "Needs_Mirroring"]
        return df

    df_v    = load_std(QC_DIR    / "VERIFIED_LIST.csv",              "verified")
    df_morph= load_std(MORPH_DIR / "MORPHOLOGY_RECOVERY_REPORT.csv", "morphology")
    df_mirr = load_std(MIRROR_DIR/ "MIRROR_RECOVERY_REPORT.csv",     "mirror")

    # Mirror > Morphology > Verified — keep highest scoring entry per slice
    combined = pd.concat([df_mirr, df_morph, df_v], ignore_index=True)
    combined = combined.sort_values(
        ["Animal", "HiRes_ID", "Score"], ascending=[True, True, False]
    )
    final = (combined
             .drop_duplicates(subset=["Animal", "HiRes_ID"], keep="first")
             .sort_values(["Animal", "Correct_ID"]))

    out = REPORT_DIR / "PROJECT_GOLDEN_MASTER_LIST.csv"
    final.to_csv(out, index=False)
    print(f"  {len(final)} unique slices  |  "
          f"{final['Needs_Mirroring'].sum()} need flipping")
    print(f"  Saved: {out}")
    return final

# =============================================================================
# STAGE 11 — Visual audit gallery from golden master
# =============================================================================

def stage11_audit_gallery():
    print("\n=== Stage 11: Final audit gallery ===")
    AUDIT_DIR.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(REPORT_DIR / "PROJECT_GOLDEN_MASTER_LIST.csv")
    for _, row in tqdm(df.iterrows(), total=len(df)):
        animal, hi_id, correct_id = row["Animal"], row["HiRes_ID"], row["Correct_ID"]
        mirrored = row["Needs_Mirroring"]
        score    = row["Score"]

        gen_files = list((GEN_BASE / animal).glob(f"*{hi_id}.jpg"))
        ref_folder = find_ref_folder(animal)
        if not ref_folder or not gen_files:
            continue
        ref_files = list(ref_folder.glob(f"*{correct_id}.jpg"))
        if not ref_files:
            continue

        img_gen = io.imread(gen_files[0])
        img_ref = io.imread(ref_files[0])
        display_gen = np.fliplr(img_gen) if mirrored else img_gen

        fig, axes = plt.subplots(1, 2, figsize=(16, 8))
        axes[0].imshow(img_ref)
        axes[0].set_title(f"REFERENCE: {correct_id}", fontsize=15,
                          color="blue", fontweight="bold")
        axes[0].axis("off")
        axes[1].imshow(display_gen)
        axes[1].set_title(
            f"GENERATED: {hi_id}" + (" (FLIPPED)" if mirrored else "") +
            f"\nScore: {score:.4f}", fontsize=15, color="darkgreen"
        )
        axes[1].axis("off")
        plt.suptitle(f"{animal}", fontsize=20, fontweight="bold")
        plt.savefig(AUDIT_DIR / f"AUDIT_{animal}_REF-{correct_id}_GEN-{hi_id}.png",
                    bbox_inches="tight")
        plt.close()
    print(f"  Gallery saved to: {AUDIT_DIR}")

# =============================================================================
# STAGE 12 — Apply to split_8bit TIFFs
# =============================================================================

def stage12_apply_split8bit():
    print("\n=== Stage 12: Apply to split_8bit TIFFs ===")
    FINAL_PREPPED.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(REPORT_DIR / "PROJECT_GOLDEN_MASTER_LIST.csv")
    all_animal_paths = {p.name: p for p in SPLIT_8BIT_BASE.rglob("*") if p.is_dir()}
    log = []

    for _, row in tqdm(df.iterrows(), total=len(df)):
        animal     = str(row["Animal"])
        current_id = str(row["HiRes_ID"])
        correct_id = str(row["Correct_ID"])
        mirror     = bool(row["Needs_Mirroring"])

        if animal not in all_animal_paths:
            continue
        src_dir  = all_animal_paths[animal]
        rel      = src_dir.relative_to(SPLIT_8BIT_BASE)
        dst_dir  = FINAL_PREPPED / rel
        dst_dir.mkdir(parents=True, exist_ok=True)

        channels_ok = 0
        for ch in ["C1", "C2", "C3"]:
            src = src_dir / f"{animal}_{current_id}-{ch}.tif"
            dst = dst_dir / f"{animal}_{correct_id}-{ch}.tif"
            if not src.exists():
                continue
            try:
                img = io.imread(src)
                if mirror:
                    img = np.fliplr(img)
                io.imsave(dst, img, check_contrast=False, plugin="tifffile")
                del img
                gc.collect()
                channels_ok += 1
            except Exception as e:
                print(f"  Error {src.name}: {e}")

        log.append({
            "Animal": animal, "Original_ID": current_id,
            "New_ID": correct_id, "Mirrored": mirror,
            "Channels": channels_ok,
            "Status": "OK" if channels_ok == 3 else "Partial",
        })

    pd.DataFrame(log).to_csv(FINAL_PREPPED / "Processing_Log.csv", index=False)
    print(f"  Done. Log: {FINAL_PREPPED / 'Processing_Log.csv'}")

# =============================================================================
# STAGE 13 — Apply to C1 CPN prediction PNGs (in-place)
# =============================================================================

def stage13_apply_c1_pngs():
    print("\n=== Stage 13: Apply to C1 prediction PNGs ===")
    df = pd.read_csv(REPORT_DIR / "PROJECT_GOLDEN_MASTER_LIST.csv")
    all_pred = {p.name: p for p in CPN_OUTPUT_C1.rglob("*") if p.is_dir()}

    for _, row in tqdm(df.iterrows(), total=len(df)):
        animal, cur, cor, mirror = (str(row["Animal"]), str(row["HiRes_ID"]),
                                    str(row["Correct_ID"]), bool(row["Needs_Mirroring"]))
        if animal not in all_pred:
            continue
        tgt = all_pred[animal]
        old_path = tgt / f"all_predictions_{animal}_{cur}-C1.png"
        new_path = tgt / f"all_predictions_{animal}_{cor}-C1.png"

        if old_path.exists():
            if old_path != new_path:
                os.rename(old_path, new_path)
            if mirror:
                try:
                    img = io.imread(new_path)
                    io.imsave(new_path, np.fliplr(img), check_contrast=False)
                    del img; gc.collect()
                except Exception as e:
                    print(f"  Error mirroring {new_path.name}: {e}")
    print("  Done.")

# =============================================================================
# STAGE 14 — Apply to C2 CPN prediction PNGs (in-place)
# =============================================================================

def stage14_apply_c2_pngs():
    print("\n=== Stage 14: Apply to C2 prediction PNGs ===")
    df = pd.read_csv(REPORT_DIR / "PROJECT_GOLDEN_MASTER_LIST.csv")
    all_pred = {p.name: p for p in CPN_OUTPUT_C2.rglob("*") if p.is_dir()}

    for _, row in tqdm(df.iterrows(), total=len(df)):
        animal, cur, cor, mirror = (str(row["Animal"]), str(row["HiRes_ID"]),
                                    str(row["Correct_ID"]), bool(row["Needs_Mirroring"]))
        if animal not in all_pred:
            continue
        tgt = all_pred[animal]
        old_path = tgt / f"all_predictions_{animal}_{cur}-C2.png"
        new_path = tgt / f"all_predictions_{animal}_{cor}-C2.png"

        if old_path.exists():
            if old_path != new_path:
                os.rename(old_path, new_path)
            if mirror:
                try:
                    img = io.imread(new_path)
                    io.imsave(new_path, np.fliplr(img), check_contrast=False)
                    del img; gc.collect()
                except Exception as e:
                    print(f"  Error mirroring {new_path.name}: {e}")
    print("  Done.")

# =============================================================================
# STAGE 15 — Rename counts CSVs
# =============================================================================

def stage15_rename_count_csvs():
    print("\n=== Stage 15: Rename counts CSVs ===")
    df = pd.read_csv(REPORT_DIR / "PROJECT_GOLDEN_MASTER_LIST.csv")

    for _, row in tqdm(df.iterrows(), total=len(df)):
        animal = str(row["Animal"])
        cur    = str(row["HiRes_ID"])
        cor    = str(row["Correct_ID"])

        counts_dir = DATA_BASE / animal / "counts"
        if not counts_dir.exists():
            found = list(DATA_BASE.rglob(f"{animal}/counts"))
            if not found:
                continue
            counts_dir = found[0]

        for ch in ["C1", "C2"]:
            old = counts_dir / f"{animal}_{cur}-{ch}.csv"
            new = counts_dir / f"{animal}_{cor}-{ch}.csv"
            if old.exists() and old != new:
                try:
                    os.rename(old, new)
                except Exception as e:
                    print(f"  Error renaming {old.name}: {e}")
    print("  Done.")

# =============================================================================
# STAGE 16 — Copy + mirror hiRes TIFFs → HIRES_FINAL
# =============================================================================

def stage16_copy_hires():
    print("\n=== Stage 16: Copy + mirror hiRes TIFFs ===")
    HIRES_FINAL.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(REPORT_DIR / "PROJECT_GOLDEN_MASTER_LIST.csv")
    all_animals = {p.name: p for p in DATA_BASE.iterdir() if p.is_dir()}

    for _, row in tqdm(df.iterrows(), total=len(df)):
        animal, cur, cor, mirror = (str(row["Animal"]), str(row["HiRes_ID"]),
                                    str(row["Correct_ID"]), bool(row["Needs_Mirroring"]))
        if animal not in all_animals:
            continue
        src_dir = DATA_BASE / animal / "hiRes"
        dst_dir = HIRES_FINAL / animal / "hiRes"
        dst_dir.mkdir(parents=True, exist_ok=True)

        for ch in ["C1", "C2", "C3"]:
            src = src_dir / f"{animal}_{cur}-{ch}.tif"
            dst = dst_dir / f"{animal}_{cor}-{ch}.tif"
            if not src.exists():
                continue
            try:
                if mirror:
                    img = io.imread(src)
                    io.imsave(dst, np.fliplr(img), check_contrast=False, plugin="tifffile")
                    del img; gc.collect()
                else:
                    shutil.copy2(src, dst)
            except Exception as e:
                print(f"  Error {src.name}: {e}")
    print(f"  Done. Output: {HIRES_FINAL}")

# =============================================================================
# STAGE 17 — Integrity audit
# =============================================================================

def stage17_integrity_audit():
    print("\n=== Stage 17: Integrity audit ===")
    df = pd.read_csv(REPORT_DIR / "PROJECT_GOLDEN_MASTER_LIST.csv")
    errors = []

    for _, row in tqdm(df.iterrows(), total=len(df)):
        animal, old_id, new_id = str(row["Animal"]), str(row["HiRes_ID"]), str(row["Correct_ID"])
        for ch in ["C1", "C2", "C3"]:
            orig = DATA_BASE  / animal / "hiRes" / f"{animal}_{old_id}-{ch}.tif"
            new  = HIRES_FINAL / animal / "hiRes" / f"{animal}_{new_id}-{ch}.tif"
            status = "OK"
            if not orig.exists():
                status = "Missing in original"
            elif not new.exists():
                status = "FAILED TO TRANSFER"
            elif abs(orig.stat().st_size - new.stat().st_size) / orig.stat().st_size > 0.2:
                status = "Size mismatch"
            if status != "OK":
                errors.append({"Animal": animal, "File": orig.name,
                                "Expected": new.name, "Status": status})

    if not errors:
        print("  PASS — all files transferred correctly.")
    else:
        df_err = pd.DataFrame(errors)
        out = HIRES_FINAL / "TRANSFER_ERRORS_LOG.csv"
        df_err.to_csv(out, index=False)
        print(f"  {len(errors)} issues. Saved: {out}")
        print(df_err.to_string(index=False))

# =============================================================================
# STAGE 18 — Safe structure swap
# =============================================================================

def stage18_structure_swap():
    print("\n=== Stage 18: Safe structure swap ===")
    if not DATA_BASE.exists() or not HIRES_FINAL.exists():
        print("  ERROR: DATA_BASE or HIRES_FINAL not found.")
        return

    sample = next(HIRES_FINAL.iterdir(), None)
    if sample and not (sample / "hiRes").exists():
        print(f"  WARNING: {sample.name} missing 'hiRes' subfolder — aborting.")
        return

    backup = DATA_BASE.parent / (DATA_BASE.name + "_OLD_UNSORTED_BACKUP")
    if backup.exists():
        backup = DATA_BASE.parent / (DATA_BASE.name + "_OLD_UNSORTED_BACKUP_v2")

    try:
        os.rename(DATA_BASE, backup)
        os.rename(HIRES_FINAL, DATA_BASE)
        print(f"  New DATA: {DATA_BASE}")
        print(f"  Backup:   {backup}")
    except Exception as e:
        print(f"  ERROR during swap: {e}")

# =============================================================================
# STAGE 19 — Restore subfolders from backup
# =============================================================================

def stage19_restore_subfolders():
    print("\n=== Stage 19: Restore subfolders from backup ===")
    backup = DATA_BASE.parent / (DATA_BASE.name + "_OLD_UNSORTED_BACKUP")
    if not backup.exists():
        backup = DATA_BASE.parent / (DATA_BASE.name + "_OLD_UNSORTED_BACKUP_v2")
    if not backup.exists():
        print("  ERROR: backup directory not found.")
        return

    for animal_folder in tqdm(list(backup.iterdir()), desc="Animals"):
        if not animal_folder.is_dir():
            continue
        target = DATA_BASE / animal_folder.name
        target.mkdir(parents=True, exist_ok=True)
        for folder_name in FOLDERS_TO_RESTORE:
            src = animal_folder / folder_name
            dst = target / folder_name
            if src.exists():
                if not dst.exists():
                    try:
                        os.rename(src, dst)
                    except Exception as e:
                        print(f"  Error restoring {animal_folder.name}/{folder_name}: {e}")
                else:
                    print(f"  SKIP (already exists): {animal_folder.name}/{folder_name}")
    print("  Done.")

# =============================================================================
# STAGE 20 — Apply to original multi-channel TIFFs
# =============================================================================

def stage20_apply_originals():
    print("\n=== Stage 20: Apply to original multi-channel TIFFs ===")
    ORIGINALS_RENAMED.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(REPORT_DIR / "PROJECT_GOLDEN_MASTER_LIST.csv")

    for _, row in tqdm(df.iterrows(), total=len(df)):
        animal, cur, cor, mirror = (str(row["Animal"]), str(row["HiRes_ID"]),
                                    str(row["Correct_ID"]), bool(row["Needs_Mirroring"]))

        matches = (list(SOURCE_ROOT.glob(f"**/{animal}/{animal}_{cur}.tiff")) or
                   list(SOURCE_ROOT.glob(f"**/{animal}_{cur}.tiff")))
        if not matches:
            continue
        src = matches[0]
        group_name  = src.parent.parent.name
        dst_dir     = ORIGINALS_RENAMED / group_name / animal
        dst_dir.mkdir(parents=True, exist_ok=True)
        dst = dst_dir / f"{animal}_{cor}.tiff"

        try:
            if mirror:
                img = io.imread(src)
                io.imsave(dst, np.fliplr(img), check_contrast=False, plugin="tifffile")
                del img; gc.collect()
            elif not dst.exists():
                shutil.copy2(src, dst)
        except Exception as e:
            print(f"  Error {src.name}: {e}")
    print(f"  Done. Output: {ORIGINALS_RENAMED}")

# =============================================================================
# STAGE 21 — C3 symmetry audit
# =============================================================================

def stage21_c3_audit():
    print(f"\n=== Stage 21: C3 symmetry audit (expected side: {EXPECTED_SIDE}) ===")
    all_tiffs = list(ORIGINALS_RENAMED.rglob("*.tiff"))
    print(f"  {len(all_tiffs)} files to check.")
    log = []

    for tiff_path in tqdm(all_tiffs):
        try:
            img = io.imread(tiff_path)
            if img.ndim == 3:
                c3 = img[2, :, :] if img.shape[0] <= 4 else img[:, :, 2]
            else:
                continue

            mid   = c3.shape[1] // 2
            l_mean = float(np.mean(c3[:, :mid]))
            r_mean = float(np.mean(c3[:, mid:]))
            ratio  = max(l_mean, r_mean) / max(min(l_mean, r_mean), 1)
            actual = "left" if l_mean > r_mean else "right"

            log.append({
                "Animal": tiff_path.parent.name, "File": tiff_path.name,
                "Full_Path": str(tiff_path),
                "Left_Mean": round(l_mean, 2), "Right_Mean": round(r_mean, 2),
                "Ratio": round(ratio, 2), "Signal_Side": actual,
                "Needs_Flip_Check": "YES" if actual != EXPECTED_SIDE else "no",
            })
            del img, c3; gc.collect()
        except Exception as e:
            print(f"  Error {tiff_path.name}: {e}")

    df = pd.DataFrame(log)
    out = ORIGINALS_RENAMED / "C3_Symmetry_Audit.csv"
    df.to_csv(out, index=False)
    flagged = (df["Needs_Flip_Check"] == "YES").sum()
    print(f"  {len(df)} files audited, {flagged} flagged. Saved: {out}")
    if flagged:
        print(df[df["Needs_Flip_Check"] == "YES"].to_string(index=False))

# =============================================================================
# STAGE 22 — Mirror C3-flagged files in-place
# =============================================================================

def stage22_mirror_flagged():
    print("\n=== Stage 22: Mirror C3-flagged files ===")
    df = pd.read_csv(ORIGINALS_RENAMED / "C3_Symmetry_Audit.csv")
    to_flip = df[df["Needs_Flip_Check"] == "YES"]
    print(f"  {len(to_flip)} files to mirror.")

    for _, row in tqdm(to_flip.iterrows(), total=len(to_flip)):
        target = ORIGINALS_RENAMED / row["Animal"] / row["File"]
        if not target.exists():
            matches = list(ORIGINALS_RENAMED.rglob(row["File"]))
            if not matches:
                print(f"  WARNING: {row['File']} not found.")
                continue
            target = matches[0]
        try:
            img = io.imread(target)
            io.imsave(target, np.fliplr(img), check_contrast=False, plugin="tifffile")
            del img; gc.collect()
        except Exception as e:
            print(f"  Error {row['File']}: {e}")
    print("  Done.")

# =============================================================================
# STAGE 23 — Final orientation verification
# =============================================================================

def stage23_verify_orientation():
    print(f"\n=== Stage 23: Orientation verification (expected: {EXPECTED_SIDE}) ===")
    all_tiffs = list(ORIGINALS_RENAMED.rglob("*.tiff"))
    log = []

    for tiff_path in tqdm(all_tiffs):
        try:
            img = io.imread(tiff_path)
            c3  = img[2, :, :] if (img.ndim == 3 and img.shape[0] < img.shape[-1]) else img[:, :, 2]
            mid = c3.shape[1] // 2
            l_mean = float(np.mean(c3[:, :mid]))
            r_mean = float(np.mean(c3[:, mid:]))
            ratio  = max(l_mean, r_mean) / (min(l_mean, r_mean) + 1e-6)
            actual = "left" if l_mean > r_mean else "right"
            if ratio < 1.2:
                status = "AMBIGUOUS"
            elif actual == EXPECTED_SIDE:
                status = "PASS"
            else:
                status = "FAIL"
            log.append({
                "Animal": tiff_path.parent.name, "File": tiff_path.name,
                "Left_Mean": round(l_mean, 4), "Right_Mean": round(r_mean, 4),
                "Ratio": round(ratio, 2), "Signal_Side": actual, "Final_Status": status,
            })
            del img, c3; gc.collect()
        except Exception as e:
            print(f"  Error {tiff_path.name}: {e}")

    df = pd.DataFrame(log)
    out = ORIGINALS_RENAMED / "FINAL_ORIENTATION_VERIFICATION.csv"
    df.to_csv(out, index=False)
    print(df["Final_Status"].value_counts().to_string())
    problems = df[df["Final_Status"] != "PASS"]
    if not problems.empty:
        print(f"\n  {len(problems)} files require manual review:")
        print(problems.sort_values("Final_Status").to_string(index=False))
    print(f"  Saved: {out}")

# =============================================================================
# STAGE 24 — Visual comparison gallery vs reference
# =============================================================================

def stage24_comparison_gallery():
    print("\n=== Stage 24: Comparison gallery ===")
    GALLERY_OUT.mkdir(parents=True, exist_ok=True)
    all_tiffs = sorted(ORIGINALS_RENAMED.rglob("*.tiff"))
    THUMB_H   = 800

    for tiff_path in tqdm(all_tiffs):
        try:
            img = io.imread(tiff_path)
            c3  = img[2, :, :] if img.shape[0] < img.shape[-1] else img[:, :, 2]
            aspect = c3.shape[1] / c3.shape[0]
            new_w  = int(THUMB_H * aspect)
            rsc = transform.resize(c3, (THUMB_H, new_w), anti_aliasing=True)
            rsc = util.img_as_ubyte(
                (rsc - rsc.min()) / (rsc.max() - rsc.min() + 1e-6)
            )
            new_pil = Image.fromarray(rsc).convert("RGB")

            ref_name = tiff_path.stem + ".jpg"
            ref_matches = list(REF_BASE.rglob(ref_name))
            if ref_matches:
                ref_pil = Image.open(ref_matches[0]).resize((new_w, THUMB_H))
            else:
                ref_pil = Image.new("RGB", (new_w, THUMB_H), (100, 0, 0))

            canvas = Image.new("RGB", (new_w * 2 + 10, THUMB_H + 60), (30, 30, 30))
            canvas.paste(ref_pil, (0, 0))
            canvas.paste(new_pil, (new_w + 10, 0))
            draw = ImageDraw.Draw(canvas)
            draw.text((10, THUMB_H + 10),  "ORIGINAL REFERENCE", fill="yellow")
            draw.text((new_w + 20, THUMB_H + 10), "NEW PROCESSED (C3)", fill="cyan")
            draw.text((10, THUMB_H + 35),  tiff_path.name, fill="white")
            canvas.save(GALLERY_OUT / f"Compare_{tiff_path.stem}.jpg", quality=85)

            del img, c3, rsc, new_pil, ref_pil, canvas; gc.collect()
        except Exception as e:
            print(f"  Error {tiff_path.name}: {e}")
    print(f"  Gallery: {GALLERY_OUT}")

# =============================================================================
# STAGE 25 — Manual flip of residual files
# =============================================================================

def stage25_manual_flips():
    print(f"\n=== Stage 25: Manual flips ({len(MANUAL_FLIP_LIST)} files) ===")
    if not MANUAL_FLIP_LIST:
        print("  MANUAL_FLIP_LIST is empty — nothing to do.")
        print("  Populate it from your Stage 24 gallery inspection before running.")
        return

    for filename in tqdm(MANUAL_FLIP_LIST):
        matches = list(ORIGINALS_RENAMED.rglob(filename))
        if not matches:
            print(f"  WARNING: {filename} not found.")
            continue
        target = matches[0]
        try:
            img = io.imread(target)
            io.imsave(target, np.fliplr(img), check_contrast=False, plugin="tifffile")
            del img; gc.collect()
        except Exception as e:
            print(f"  Error {filename}: {e}")
    print("  Done.")

# =============================================================================
# STAGE 26 — Produce FINAL_TIFF_TRANSFORMATION_LOG.csv
# =============================================================================

def stage26_transformation_log():
    print("\n=== Stage 26: FINAL_TIFF_TRANSFORMATION_LOG.csv ===")

    df_master = pd.read_csv(REPORT_DIR / "PROJECT_GOLDEN_MASTER_LIST.csv")
    df_log = df_master[["Animal", "HiRes_ID", "Correct_ID", "Needs_Mirroring"]].copy()
    df_log.columns = ["Animal", "Original_ID", "Final_ID", "Flipped_in_Step1"]
    df_log["Final_Filename"] = df_log.apply(
        lambda r: f"{r['Animal']}_{r['Final_ID']}.tiff", axis=1
    )

    audit_csv = ORIGINALS_RENAMED / "C3_Symmetry_Audit.csv"
    if audit_csv.exists():
        df_audit = pd.read_csv(audit_csv)
        flipped_in_audit = df_audit[df_audit["Needs_Flip_Check"] == "YES"]["File"].tolist()
    else:
        print("  Warning: C3_Symmetry_Audit.csv not found.")
        flipped_in_audit = []

    df_log["Flipped_in_C3_Audit"]    = df_log["Final_Filename"].isin(flipped_in_audit)
    df_log["Flipped_in_Manual_Final"]= df_log["Final_Filename"].isin(MANUAL_FLIP_LIST)

    def net_change(row):
        n_flips = sum([
            row["Flipped_in_Step1"],
            row["Flipped_in_C3_Audit"],
            row["Flipped_in_Manual_Final"],
        ])
        return "Mirrored" if n_flips % 2 != 0 else "Original Orientation"

    df_log["Net_Orientation_Change"] = df_log.apply(net_change, axis=1)

    out = ORIGINALS_RENAMED / "FINAL_TIFF_TRANSFORMATION_LOG.csv"
    df_log.to_csv(out, index=False)
    mirrored = (df_log["Net_Orientation_Change"] == "Mirrored").sum()
    print(f"  {len(df_log)} entries  |  {mirrored} net-mirrored")
    print(f"  Saved: {out}")
    print(df_log.head(10).to_string(index=False))

# =============================================================================
# ENTRY POINT — run stages in order
# =============================================================================

if __name__ == "__main__":
    # Comment out stages you have already completed or wish to skip.
    # Each stage reads the CSV output of the previous one.
    # Stages 11, 24 are visual-only and can be skipped on re-runs.
    # Stop after Stage 11 to manually inspect the audit gallery before
    # committing to the file operations in Stages 12–20.

    stage1_ssim_crossmatch()
    stage2_rigorous_analysis()
    stage3_recovery()
    stage4_rename_list()
    stage5_qc_split()
    stage6_morphology_recovery()
    stage7_morphology_gallery()     # visual — inspect before continuing
    stage8_mirror_recovery()
    stage9_mirror_gallery()         # visual — inspect before continuing
    stage10_golden_master()
    stage11_audit_gallery()         # visual — inspect before committing to writes

    # File operations — run only after visual review confirms the golden master
    stage12_apply_split8bit()
    stage13_apply_c1_pngs()
    stage14_apply_c2_pngs()
    stage15_rename_count_csvs()
    stage16_copy_hires()
    stage17_integrity_audit()
    stage18_structure_swap()        # destructive — backs up DATA and swaps in HIRES_FINAL
    stage19_restore_subfolders()

    stage20_apply_originals()
    stage21_c3_audit()
    stage22_mirror_flagged()
    stage23_verify_orientation()
    stage24_comparison_gallery()    # visual — populate MANUAL_FLIP_LIST from here
    stage25_manual_flips()          # requires MANUAL_FLIP_LIST to be populated
    stage26_transformation_log()
